displayName=Gauntlet Toolkit
author=supernate91
description=Comprehensive all-in-one plugin for The Gauntlet with map, stats, and overlays.
tags=the,gauntlet,corrupted,toolkit
plugins=nr.gauntlet.GauntletToolkitPlugin
