displayName=The Gauntlet - Enhanced
author=rdutta
description=The Original All-in-one plugin for The Gauntlet. BUT ENHANCED.
tags=the,gauntlet,corrupted,enhanced
plugins=nr.gauntlet.TheGauntletPlugin
